# Generated by Django 4.2.6 on 2024-08-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='wind',
            field=models.FloatField(null=True),
        ),
    ]
